#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(hostname) == "laptop" &&  $(xrandr -q | grep '\bconnected\b' | wc -l) == 2 ]] 
then
  mons -e left
  bspc monitor HDMI-1 -d VII VIII
  bspc monitor LVDS-1 -d IX X
else
  bspc monitor -d VII VIII IX X
fi

bspc config border_width        0
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch.sh

bspc rule -a scratchpad sticky=on state=floating hidden=on

# check scratchpad already running
[ "$(ps -x | grep -c 'scratchpad')" -eq "1" ] && st -c scratchpad -e ~/scripts/scratch &
